version: '3'

services:
  db:
    image: postgres:latest
    container_name: gq_database
    ports:
      - "5432:5432"
    volumes:
      - db_v1:/var/lib/postgresql/data
    env_file:
      - ./config/dev.env
    networks: 
      - db_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: gq_admin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: gql@gql.com
      PGADMIN_DEFAULT_PASSWORD: gql
    ports:
      - "8080:80"
    networks: 
      - db_network

  webapp:
    build:
      context: .
      dockerfile: "{{project_name}}.dockerfile"
    container_name: gq_webapp
    depends_on:
      - db
    command: ["./run.sh"]
    volumes:
      - static:/staticfiles
    restart: always
    env_file:
      - ./config/dev.env
    environment:
      GQ_ENV: production
    networks: 
      - db_network
      - nginx_network

  nginx:
    build:
      context: .
      dockerfile: "nginx.dockerfile"
    container_name: gq_server
    ports:
      - "80:80"
    restart: always
    volumes:
      - static:/usr/share/nginx/static
    networks: 
      - nginx_network
    depends_on:
      - webapp

networks:
  db_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  db_v1:
  static:
